project:
  type: website
  preview:
    port: 4200
    browser: false

website:
  title: "Dylan Spicker"
  site-url: "https://dylanspicker.com/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Me"
    right:
      - href: work.qmd
        text: "My Work"
      - href: teaching.qmd
        text: "My Teaching"
      - href: blog.qmd
        text: "My Thoughts"
format:
  html:
      theme: simplex
      css: styles.css
      toc: false
      page-layout: full



