project:
  type: website
  preview:
    port: 4200
    browser: false
  # post-render:
  #     - "xcopy /s /e /h applets _site"
website:
  title: "Dylan Spicker"
  site-url: "https://dylanspicker.com/"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: work.qmd
        text: "My Work"
      - href: teaching.qmd
        text: "My Teaching"
      - href: blog.qmd
        text: "My Thoughts"
format:
  html:
      theme: cosmo
      css: styles.css
      toc: false
      page-layout: full
      include-before-body: header.html



