---
title: "About Me"
---
## Relevant Links
- My [Google Scholar](https://scholar.google.com/citations?user=L9AenZ0AAAAJ&hl=en){target="_blank"} has an up to date set of my publications and preprints.
- My [YouTube Channel](https://www.youtube.com/channel/UC_xQeFdhjymQzmW4WKYtlpQ/featured){target="_blank"} contains lecture and tutorial videos from courses I have taught, illustrating my teaching style.
- My [CV](/pdf/CV.pdf){target="_BLANK"} is available in PDF form (last updated October, 2022).
- My [Teaching Philosophy Statement](/thoughts/teaching-philosophy-statement/index.qmd) has been published as a blog post.
- My [Research Philosophy Statement](/thoughts/research-philosophy-statement/index.qmd) has been published as a blog post.

## About Me
My research focuses on areas of causal inference, and specifically methodologies related to dynamic treatment regimes. During my graduate studies, my research focused on measurement error and causal inference. Briefly, measurement error occurs whenever we are interested in measuring something and we do a bad job of it. This happens in almost every study that is run, and unfortunately means that the conclusions that we draw may not be accurate: statistical work on measurement error tries to correct this. Causal inference asks questions of the form “Does X cause Y?” [For instance “Does smoking cause lung cancer?” (yes, it does).] I have a keen interest in providing a theoretical basis for (comparatively) straightforward methods, which are easy to use for non-statisticians, while exhibiting provably good theoretical properties. During my postdoc, I explored problems related to privacy and dynamic treatment regimes, where I sought to determine ways that individual's personal health data can be protected, while gleaning the useful insights that we seek. 

Outside of causal inference and measurement error, I am interested in machine learning, and in particular in trying to establish a statistical basis for novel machine learning techniques (including questions related to inference, interpretability, and model selection).

I previously did an undergraduate degree in Finance and Mathematics at Queen’s University (I transferred there after completing my first year at Waterloo/Laurier in the ‘Double Degree’ program), and a Master’s of Statistics at Waterloo.

Outside of my research, I pay very close attention to sports, mostly hockey, (and how statistics is, or should be, applied there), play music (without any connection to statistics), and enjoy board/video games (with varying degrees of statistical relevance).

## Contacting Me
- Email: See my departmental website.
- [LinkedIn](https://www.linkedin.com/in/dylanspicker/){target="_blank"}: In case anyone is still using this.