---
title: "STAT 231"
subtitle: "Statistics"
semester: "2021 Winter"
school: "University of Waterloo"
---

## Weekly Tutorials
1. [**Week 002**](https://www.youtube.com/watch?v=F3Z-5s30D4A&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=1){target="_BLANK"}: This tutorial goes over the concepts from weeks one and two in the course. As promised, the timestamps for the sections are:
    * Part II - Key Takeaways Since Last Time (4:08)
    * Part III - Example Problem. (7:36)
    * Part IV - Thinking Statistically. (27:26)
    * Part V - Outside of STAT 231. (33:25)
    * Part VI - Looking Forward. (37:50)
1. [**Week 003**](https://www.youtube.com/watch?v=KbiNSGX2-Cc&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=2){target="_BLANK"}: Hi everyone! This weeks tutorial breaks the format that I set out last week (oops!) because I did not want to overwhelm. My solutions to the problems (see attached pdf file!) ended up running long, and so I figured I would save you sitting through the recap/look forward/thinking statistically sections of this video [I had a "magic trick" filmed to explain likelihood, which, if time permits later in the course, I can certainly share (see the attached picture if you want a spoiler!)]. I know that the longer tutorial may feel like additional stress, and so I want to make three things with this clear: (1) I have tried to include as many steps in the solution as I could to provide a very thorough background on the problem. I have tried to talk slow, and not skip details, and so hopefully the longer video is explained by this; (2) I wanted to provide more example problems, particularly this week covering MLE, since they are the first "mathematical topic" we are covering. If you feel very comfortable with them, and you take a look at the questions and feel okay with those, feel free to skim the video -- you can certainly do well in this course without it. (3) I will make it up to you with a shorter video on a topic that warrants it! I wanted to remind you all that if you have any questions regarding the content in the tutorials, you can always reach me by email (dylan.spicker@uwaterloo.ca) or on Piazza, and if you have any feedback at all, please feel free to reach out. Ultimately, it is my hope to try to use the tutorials to form some of "in-class" relationship that we are missing out on, being online, and if there is anyway I can improve that for you, please let me know! Thanks, and I hope you all have an excellent weekend and week!
1. [**Week 004**](https://www.youtube.com/watch?v=YVeNbthXki8&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=3){target="_BLANK"}: Hi everyone! Back to a more regular tutorial (and this time much shorter). As promised, the relevant time stamps are included below, and the necessary resources are posted on the course website! 
    * 0:00​ - Part I - Introduction and Video Schedule
    * 1:35​ - Part II - Key Takeaways Since Last Time
    * 4:50​ - Part III - Example Problem
    * 20:10​ - Part IV - Build your Intuition
    * 28:02​ - Part V - Looking Forward
    * The study PDF is uploaded on LEARN and is available: [https://www.nejm.org/doi/pdf/10.1056/NEJMoa2035389](https://www.nejm.org/doi/pdf/10.1056/NEJMoa2035389)
    * The protocol PDF is uploaded on LEARN and is available: [https://www.nejm.org/doi/suppl/10.1056/NEJMoa2035389/suppl_file/nejmoa2035389_protocol.pdf](https://www.nejm.org/doi/suppl/10.1056/NEJMoa2035389/suppl_file/nejmoa2035389_protocol.pdf)
    * The qqplot Shiny application is available: [https://shiny.math.uwaterloo.ca/sas/stat231/qqplots/](https://shiny.math.uwaterloo.ca/sas/stat231/qqplots/)
1. [**Week 005**](https://www.youtube.com/watch?v=_euR1kVMQ5A&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=4){target="_BLANK"}: Hi everyone! In this week's tutorial we are looking at the "Sampling Distribution" (using a giant box of expired chips that my mom gave to me, for some reason), and we investigate some tricks for manipulating likelihood functions (by request from you!). This is a fairly short video before reading week (please, try to enjoy your week away!), and the goal is to prepare you well for our deep dive into intervals in the week back. As always, timestamps are given below. 
    * 0:00 - Part 0 - Introduction and Video Schedule
    * 1:08 - Part I - Example Problem
    * 9:16 - Part II - Tips and Tricks
    * 19:47 - Part III - Looking Forward
1. [**Week 006**](https://www.youtube.com/watch?v=62zjWL0bTRU&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=5){target="_BLANK"}: Hi everyone! This time, our tutorial covers confidence intervals and likelihood intervals. My apologies for the technical issues in the middle! Please reach out if you need more detail in answering the questions! Timestamps!
    * 0:00​ - Part 0 - Introduction.
    * 1:16​ - Part I - Takeaways Since Last Time.
    * 2:59​ - Part II - Thinking Statistically.
    * 12:40​ - Part III - Tips and Tricks.
    * 16:17​ - Part IV - Example Problem (Sorry!).
    * 17:20​ - Part V - Looking Forward.
1. [**Week 007**](https://www.youtube.com/watch?v=_8QsNskn8NE&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=6){target="_BLANK"}
1. [**Week 008**](https://www.youtube.com/watch?v=eZCXqBXmr08&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=7){target="_BLANK"}
1. [**Week 009**](https://www.youtube.com/watch?v=0eDvg2Ed_04&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=8){target="_BLANK"}
1. [**Week 010**](https://www.youtube.com/watch?v=qGijVMTGdsU&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=9){target="_BLANK"}
1. [**Week 011**](https://www.youtube.com/watch?v=GslLfy-t0qI&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=10){target="_BLANK"}
1. [**Week 012**](https://www.youtube.com/watch?v=OB_ws-DqUKw&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=11){target="_BLANK"}
1. [**Practice Quiz Solution**](https://www.youtube.com/watch?v=Oot1FwEZIbc&list=PL0Y1Z_F8RtX6uDIp-d2-Ch584l9cawVOq&index=12){target="_BLANK"}